### ISSUE TITLE
New API needed (setup broker account).

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDKLib#13]
Need this so users can set it up from the app before any buy and sell action.

**Comment by acegreen** [comment]
That currently works with:
TradeItTicketController.showFullTicketWithPublisherApp("STOCKSWIPE", symbol: self.symbol, lastPrice: lastPrice, viewController: self)

I get the select broker vc etc. Though there is no documentation on how to access the Dummy broker.

**Comment by TheAntonioReyes** [comment]
To access the dummy broker you need to use the debugging methods:  https://github.com/tradingticket/TradeItIosTicketSDKLib#debuggingsetup  there is additional methods with options for further customization in TradeItTicketController.h

And this issue should now be resolved by the methods available in TradeItAuthController.h

**Comment by acegreen** [comment]
Test Users table should show the Dummy account password, I need to dig through the requests above to notice it.
