### ISSUE TITLE
Preview button is hidden, also some cosmetics 

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDKLib#22]
I recommend the line that has the refresh to have the ticker as well and moving everything up.
In the Future, the whole thing can be scrolled up to see the button, but that is a lot of change, the above suggestion is easier.
 
![image](https://cloud.githubusercontent.com/assets/3361440/9098739/8484728c-3b80-11e5-98f6-72ab2fc43138.png)

**Comment by TheAntonioReyes** [comment]
preview button issue was resolved, spacing already covered in a separate issue
