### ISSUE TITLE
UI cosmatics

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDKLib#23]
![image](https://cloud.githubusercontent.com/assets/3361440/9501257/06ceb766-4bdf-11e5-93ee-4efb7e8b39b4.png)

**Comment by imougy** [comment]
![image](https://cloud.githubusercontent.com/assets/3361440/9501963/4f1b2168-4be3-11e5-9635-066cf03cd95e.png)

**Comment by acegreen** [comment]
How did you define the tint of that VC?

**Comment by TheAntonioReyes** [comment]
Only remaining issue for this issue is the spacing between shares and the order action field.

**Comment by TheAntonioReyes** [comment]
Spacing issue resolved
