### ISSUE TITLE
Bitcode support?

### ISSUE THREAD

**Issue by acegreen** [tradingticket/TradeItIosTicketSDKLib#25]
No need to describe that one.

**Comment by imougy** [comment]
I am getting bitten by this one now that I must release Apple Watch.
Can you please give this high priority, it was working at one point.
Thanks,

**Comment by TheAntonioReyes** [comment]
This is fixed in the latest version

**Comment by acegreen** [comment]
@TheAntonioReyes is 1.0.15 the one with the overhaul we spoke about during our Skype chat?

**Comment by TheAntonioReyes** [comment]
It is not, this is just a quick bug release. The version we talked about is getting close, it'll be a full version change as the library changes are breaking changes.
