### ISSUE TITLE
Missing documentation info

### ISSUE THREAD

**Issue by acegreen** [tradingticket/TradeItIosTicketSDKLib#26]
I added the files as described and initiated a tradeTicket as expected. Only to find out from Henry that I need an API key. Any documentation on how to use it?

Also the login info for the Dummy broker would be great.

**Comment by TheAntonioReyes** [comment]
You wont need the API Key until version 2.0 of the SDK which should be out sometime in Jan. 2016, for now you only need the publisher id.

Dummy broker documentation is here:  https://www.trade.it/documentation/tradeEmsApi#dummyBroker  I'll update our read me on the next push.
