### ISSUE TITLE
ViewController behaviour after linking broker

### ISSUE THREAD

**Issue by acegreen** [tradingticket/TradeItIosTicketSDKLib#27]
So after linking with the Dummy broker, I placed an order which went through fine as expected and I was not charged :P 

But when I try to place another trade, it now skips the select broker (as expect since its now linked) and goes directly to the order page, BUT

Then it goes back to the login screen (not the select broker) but the login screen and expects a login and then has the link/unlink at the bottom of that view. 

I don't think those buttons belong in the login view and also if the broker is already linked, no need to ask for password again.

**Comment by TheAntonioReyes** [comment]
@acegreen the only reason you're seeing the login screen again is because you don't have touch id enabled on your device or you're using the simulator. We force touch id or re-login to ensure security.

**Comment by acegreen** [comment]
AH perfect :) 

Can we closed. Ticket can be used for reference by others until documentation is updated. I’m sure someone else will ask this.
