### ISSUE TITLE
Redundant order type UI (we can also add order action to main screen)

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDKLib#4]
I like the fact that the order type is in the same main screen, perfect. If we manage to get the order action to the main screen, then we can just have the secondary screen to select the brokers.

Possible UI, when tapping on the "Short Sell" button, it should display ActionSheet to change the action.
![image](https://cloud.githubusercontent.com/assets/3361440/8948472/6666f04c-355c-11e5-9a9b-58c4f93c9393.png)

**Comment by TheAntonioReyes** [comment]
no longer needed with detail view
