### ISSUE TITLE
Crash when "turning off" broker account

### ISSUE THREAD

**Issue by acegreen** [tradingticket/TradeItIosTicketSDKLib#43]
2016-03-06 18:09:08.949 StockSwipe[32914:1428884] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2016-03-06 18:09:08.950 StockSwipe[32914:1428884] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2016-03-06 18:09:08.951 StockSwipe[32914:1428884] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2016-03-06 18:09:08.952 StockSwipe[32914:1428884] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2016-03-06 18:09:08.953 StockSwipe[32914:1428884] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2016-03-06 18:09:08.954 StockSwipe[32914:1428884] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2016-03-06 18:09:08.954 StockSwipe[32914:1428884] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2016-03-06 18:09:08.955 StockSwipe[32914:1428884] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2016-03-06 18:09:17.041 StockSwipe[32914:1428884] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFArray insertObject:atIndex:]: attempt to insert nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x03e43a14 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x0361ce02 objc_exception_throw + 50
	2   CoreFoundation                      0x03e4393d +[NSException raise:format:] + 141
	3   CoreFoundation                      0x03e3a68e -[__NSCFArray insertObject:atIndex:] + 190
	4   CoreFoundation                      0x03e3a541 -[__NSCFArray addObject:] + 65
	5   StockSwipe                          0x002560e4 RolloutClosure_closureCallee + 70214
	6   StockSwipe                          0x00254aa1 RolloutClosure_closureCallee + 64515
	7   libobjc.A.dylib                     0x036310b5 -[NSObject performSelector:withObject:withObject:] + 84
	8   UIKit                               0x044b7b79 -[UIApplication sendAction:to:from:forEvent:] + 118
	9   UIKit                               0x044b7af8 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
	10  UIKit                               0x046578f8 -[UIControl sendAction:to:forEvent:] + 79
	11  UIKit                               0x04657c78 -[UIControl _sendActionsForEvents:withEvent:] + 408
	12  UIKit                               0x048c0301 __31-[UISwitch _handleLongPressNL:]_block_invoke + 85
	13  UIKit                               0x048bee8b -[_UISwitchInternalViewNeueStyle1 _setPressed:on:animated:shouldAnimateLabels:completion:] + 281
	14  UIKit                               0x048c0263 -[UISwitch _handleLongPressNL:] + 514
	15  UIKit                               0x04a3d1fc _UIGestureRecognizerSendTargetActions + 168
	16  UIKit                               0x04a390ba _UIGestureRecognizerSendActions + 176
	17  UIKit                               0x04a36bb8 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 929
	18  UIKit                               0x04a398ab -[UIGestureRecognizer _delayedUpdateGesture] + 60
	19  UIKit                               0x04a401f4 ___UIGestureRecognizerUpdate_block_invoke904 + 86
	20  UIKit                               0x04a40061 _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 374
	21  UIKit                               0x04a2acd2 _UIGestureRecognizerUpdate + 3407
	22  UIKit                               0x04533b51 -[UIWindow _sendGesturesForEvent:] + 1559
	23  UIKit                               0x0453520a -[UIWindow sendEvent:] + 1137
	24  UIKit                               0x044d9f93 -[UIApplication sendEvent:] + 266
	25  StockSwipe                          0x0038adb4 uvSendEvents + 116
	26  UIKit                               0x044af668 _UIApplicationHandleEventQueue + 7802
	27  CoreFoundation                      0x03d5d6ff __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	28  CoreFoundation                      0x03d5338b __CFRunLoopDoSources0 + 523
	29  CoreFoundation                      0x03d527a8 __CFRunLoopRun + 1032
	30  CoreFoundation                      0x03d520e6 CFRunLoopRunSpecific + 470
	31  CoreFoundation                      0x03d51efb CFRunLoopRunInMode + 123
	32  GraphicsServices                    0x088ce664 GSEventRunModal + 192
	33  GraphicsServices                    0x088ce4a1 GSEventRun + 104
	34  UIKit                               0x044b5bfa UIApplicationMain + 160
	35  StockSwipe                          0x001b2a5c main + 140
	36  libdyld.dylib                       0x06ca6a21 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by acegreen** [comment]
Turning an account on 

2016-03-06 18:14:10.337 StockSwipe[33954:1441622] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFArray insertObject:atIndex:]: attempt to insert nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e559e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010dcd0deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e559d9d +[NSException raise:format:] + 205
	3   CoreFoundation                      0x000000010e551f22 -[__NSCFArray insertObject:atIndex:] + 178
	4   StockSwipe                          0x000000010a7f6080 RolloutClosure_closureCallee + 58963
	5   StockSwipe                          0x000000010a7f509b RolloutClosure_closureCallee + 54894
	6   UIKit                               0x000000010ec07194 -[UIApplication sendAction:to:from:forEvent:] + 92
	7   UIKit                               0x000000010ed766fc -[UIControl sendAction:to:forEvent:] + 67
	8   UIKit                               0x000000010ed769c8 -[UIControl _sendActionsForEvents:withEvent:] + 311
	9   UIKit                               0x000000010ef9a0f6 -[_UISwitchInternalViewNeueStyle1 _setPressed:on:animated:shouldAnimateLabels:completion:] + 224
	10  UIKit                               0x000000010ef9b169 -[UISwitch _handleLongPressNL:] + 452
	11  UIKit                               0x000000010f0ede73 _UIGestureRecognizerSendTargetActions + 153
	12  UIKit                               0x000000010f0ea4e5 _UIGestureRecognizerSendActions + 162
	13  UIKit                               0x000000010f0e84e2 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 843
	14  UIKit                               0x000000010f0f09a0 ___UIGestureRecognizerUpdate_block_invoke904 + 79
	15  UIKit                               0x000000010f0f083e _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 342
	16  UIKit                               0x000000010f0de101 _UIGestureRecognizerUpdate + 2634
	17  UIKit                               0x000000010ec75f8a -[UIWindow _sendGesturesForEvent:] + 1137
	18  UIKit                               0x000000010ec771c0 -[UIWindow sendEvent:] + 849
	19  UIKit                               0x000000010ec25b66 -[UIApplication sendEvent:] + 263
	20  StockSwipe                          0x000000010a9070ff uvSendEvents + 111
	21  UIKit                               0x000000010ebffd97 _UIApplicationHandleEventQueue + 6844
	22  CoreFoundation                      0x000000010e485a31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	23  CoreFoundation                      0x000000010e47b95c __CFRunLoopDoSources0 + 556
	24  CoreFoundation                      0x000000010e47ae13 __CFRunLoopRun + 867
	25  CoreFoundation                      0x000000010e47a828 CFRunLoopRunSpecific + 488
	26  GraphicsServices                    0x00000001130fdad2 GSEventRunModal + 161
	27  UIKit                               0x000000010ec05610 UIApplicationMain + 171
	28  StockSwipe                          0x000000010a761b2d main + 109
	29  libdyld.dylib                       0x000000011149c92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by danielvaughn** [comment]
@acegreen in version 2.0.2, this issue should now be fixed

**Comment by acegreen** [comment]
Will close this as it seems to have been fixed. Opened a new issue #47 regarding a related issue.
