### ISSUE TITLE
Screen redesign

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDKLib#5]
I hope you can consider similar design. Advantage:-
* One screen that has all the trading info.
* No duplicate.
* Fast to change things, taping on any button should bring an ActionSheet, except for the broker selection because it is nested.
![image](https://cloud.githubusercontent.com/assets/3361440/8952214/fa0fd6b0-3589-11e5-9d08-ad66b7fcdf2b.png)

**Comment by TheAntonioReyes** [comment]
closing as not needed with detail view
